# Generated by Django 2.1.7 on 2019-02-23 10:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='time',
            new_name='close_time',
        ),
        migrations.AddField(
            model_name='log',
            name='open_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
