# Generated by Django 2.1.7 on 2019-03-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190224_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='locker',
            name='pin',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
