# Generated by Django 2.1.7 on 2019-03-15 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_locker_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='locker',
            name='pin',
        ),
        migrations.AddField(
            model_name='pin',
            name='locker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Locker'),
        ),
    ]
